### ISSUE TITLE
Database tools

### ISSUE THREAD

**Issue by DarinBeard** [borisnliscool/bnl-housing#5]
I've been looking for a standalone property tool. This looks promising. We don't use OX, we use MySQL Async so I guess it would have to be converted. I have not looked deep into your code yet but does that seem feasable to you to do or is it too engrained to even attempt? If not, and I convert it, are you interested in offering the async version? I would be happy to share that if you wanted.

**Comment by borisnliscool** [comment]
Hey, so the reason I'm using oxmysql is because I'm also using ox_lib, and I think the performance of oxmysql is a bit better than mysql-async. I think converting should be super easy, just replacing `MySQL.update` with `MySQL.Async.execute` should work (I think). Maybe in the future I'll add a pickable option for mysql-async or oxmysql for the best customizations.

**Comment by BBFCEO** [comment]
how do i set bnl housing permissions ?

**Comment by DarinBeard** [comment]
ace

**Comment by Tino434** [comment]
hi where would i enable the admin permisions with what specific commands. and where exactly can i find it. i apologise in advance for asking a stupid question
